### ISSUE TITLE
How can I use gem'ncurses' in ruby1.9

### ISSUE THREAD

**Issue by otiai10** [otiai10/rei#1]
I want to use gem 'ncurses' or 'curses', tried to 'gem install ncurses'
and failed :(

``` shell
% sudo gem install ncurses
Building native extensions.  This could take a while...
ERROR:  Error installing ncurses:
        ERROR: Failed to build gem native extension.

        /usr/local/bin/ruby extconf.rb
checking for unistd.h... yes
checking for ncurses.h... yes
checking for wmove() in -lncurses... yes
checking for newscr()... yes
checking for TABSIZE()... yes
checking for ESCDELAY()... yes
checking for keybound()... yes
checking for curses_version()... yes
checking for tigetstr()... yes
checking for getwin()... yes
checking for putwin()... yes
checking for ungetmouse()... yes
checking for mousemask()... yes
checking for wenclose()... yes
checking for mouseinterval()... yes
checking for wmouse_trafo()... yes
checking for mcprint()... yes
checking for has_key()... yes
checking for delscreen()... yes
checking for define_key()... yes
checking for keyok()... yes
checking for resizeterm()... yes
checking for use_default_colors()... yes
checking for use_extended_names()... yes
checking for wresize()... yes
checking for attr_on()... yes
checking for attr_off()... yes
checking for attr_set()... yes
checking for chgat()... yes
checking for color_set()... yes
checking for filter()... yes
checking for intrflush()... yes
checking for mvchgat()... yes
checking for mvhline()... yes
checking for mvvline()... yes
checking for mvwchgat()... yes
checking for mvwhline()... yes
checking for mvwvline()... yes
checking for noqiflush()... yes
checking for putp()... yes
checking for qiflush()... yes
checking for scr_dump()... yes
checking for scr_init()... yes
checking for scr_restore()... yes
checking for scr_set()... yes
checking for slk_attr_off()... no
checking for slk_attr_on()... no
checking for slk_attr()... yes
checking for slk_attr_set()... yes
checking for slk_color()... yes
checking for tigetflag()... yes
checking for tigetnum()... yes
checking for use_env()... yes
checking for vidattr()... yes
checking for vid_attr()... no
checking for wattr_on()... yes
checking for wattr_off()... yes
checking for wattr_set()... yes
checking for wchgat()... yes
checking for wcolor_set()... yes
checking for getattrs()... yes
checking which debugging functions to wrap...
checking for _tracef()... no
checking for _tracedump()... no
checking for _nc_tracebits()... no
checking for _traceattr()... no
checking for _traceattr2()... no
checking for _tracechar()... no
checking for _tracechtype()... no
checking for _tracechtype2()... no
checking for _tracemouse()... no
checking for other functions that appeared after ncurses version 5.0...
checking for assume_default_colors()... yes
checking for attr_get()... yes
checking for the panel library...
checking for panel.h... yes
checking for panel_hidden() in -lpanel... yes
checking for the form library...
checking for form.h... yes
checking for new_form() in -lform... yes
creating Makefile

make
compiling panel_wrap.c
compiling ncurses_wrap.c
ncurses_wrap.c: In function ‘rbncurs_define_key’:
ncurses_wrap.c:430: warning: implicit declaration of function ‘STR2CSTR’
ncurses_wrap.c:430: warning: pointer/integer type mismatch in conditional expression
ncurses_wrap.c: In function ‘rbncurs_addnstr’:
ncurses_wrap.c:536: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_addstr’:
ncurses_wrap.c:539: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_insnstr’:
ncurses_wrap.c:899: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_insstr’:
ncurses_wrap.c:902: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvaddnstr’:
ncurses_wrap.c:958: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvaddstr’:
ncurses_wrap.c:961: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvinsnstr’:
ncurses_wrap.c:992: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvinsstr’:
ncurses_wrap.c:995: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvwaddnstr’:
ncurses_wrap.c:1023: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvwaddstr’:
ncurses_wrap.c:1026: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvwinsnstr’:
ncurses_wrap.c:1054: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_mvwinsstr’:
ncurses_wrap.c:1057: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_putp’:
ncurses_wrap.c:1121: warning: passing argument 1 of ‘putp’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_scr_dump’:
ncurses_wrap.c:1154: warning: passing argument 1 of ‘scr_dump’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_scr_init’:
ncurses_wrap.c:1159: warning: passing argument 1 of ‘scr_init’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_scr_restore’:
ncurses_wrap.c:1173: warning: passing argument 1 of ‘scr_restore’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_scr_set’:
ncurses_wrap.c:1178: warning: passing argument 1 of ‘scr_set’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_slk_set’:
ncurses_wrap.c:1226: warning: passing argument 2 of ‘slk_set’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_tigetflag’:
ncurses_wrap.c:1257: warning: passing argument 1 of ‘tigetflag’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_tigetnum’:
ncurses_wrap.c: In function ‘rbncurs_tigetnum’:
ncurses_wrap.c:1262: warning: passing argument 1 of ‘tigetnum’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_tigetstr’:
ncurses_wrap.c:1267: warning: passing argument 1 of ‘tigetstr’ makes pointer from integer without a cast
ncurses_wrap.c:1267: warning: passing argument 1 of ‘tigetstr’ makes pointer from integer without a cast
ncurses_wrap.c:1267: warning: passing argument 1 of ‘tigetstr’ makes pointer from integer without a cast
ncurses_wrap.c:1267: warning: passing argument 1 of ‘tigetstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_waddnstr’:
ncurses_wrap.c:1312: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_waddstr’:
ncurses_wrap.c:1315: warning: passing argument 2 of ‘waddnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_winsnstr’:
ncurses_wrap.c:1388: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_winsstr’:
ncurses_wrap.c:1391: warning: passing argument 2 of ‘winsnstr’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_newterm’:
ncurses_wrap.c:1493: warning: pointer/integer type mismatch in conditional expression
ncurses_wrap.c: In function ‘rbncurs_mcprint’:
ncurses_wrap.c:2143: warning: passing argument 1 of ‘mcprint’ makes pointer from integer without a cast
ncurses_wrap.c: In function ‘rbncurs_getsyx’:
ncurses_wrap.c:2214: warning: ‘x’ may be used uninitialized in this function
ncurses_wrap.c:2214: warning: ‘y’ may be used uninitialized in this function
compiling form_wrap.c
form_wrap.c: In function ‘rbncurs_m_new_form’:
form_wrap.c:395: error: ‘struct RArray’ has no member named ‘len’
form_wrap.c: In function ‘rbncurs_c_set_field_type’:
form_wrap.c:619: error: ‘struct RArray’ has no member named ‘len’
form_wrap.c:624: warning: implicit declaration of function ‘STR2CSTR’
form_wrap.c:624: warning: assignment makes pointer from integer without a cast
form_wrap.c: In function ‘rbncurs_c_set_field_buffer’:
form_wrap.c:741: warning: passing argument 3 of ‘set_field_buffer’ makes pointer from integer without a cast
form_wrap.c: In function ‘rbncurs_c_set_form_fields’:
form_wrap.c:778: error: ‘struct RArray’ has no member named ‘len’
form_wrap.c: In function ‘rbncurs_c_form_request_by_name’:
form_wrap.c:1051: warning: passing argument 1 of ‘form_request_by_name’ makes pointer from integer without a cast
form_wrap.c: In function ‘make_arg’:
form_wrap.c:1126: error: ‘struct RArray’ has no member named ‘len’
make: *** [form_wrap.o] errors 1


Gem files will remain installed in /usr/local/lib/ruby/gems/1.9.1/gems/ncurses-0.9.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.9.1/gems/ncurses-0.9.1/./gem_make.out
%
```

It seems that
installing ncurses requires function 'STR2CSTR', but it has been removed in ruby1.9.
So it failed to install ncurses gem.

:trollface:  :trollface:  :trollface: 
- reference to http://openruby.com/pages/14353120-1-dot-9-2-breaks-ncurses-str2cstr-pls-help

**Comment by otiai10** [comment]
### ncurses working with ruby 1.9.2 (Snow Leopard)

http://totalrecall.wordpress.com/2010/08/22/ncurses-working-with-ruby-1-9-2-snow-leopard/

### STR2CSTR

http://www.ruby-forum.com/topic/215406

### debian package

http://packages.debian.org/ja/sid/libncurses-ruby1.9
http://packages.debian.org/ja/sid/libncurses-ruby

### rubygems.org

https://rubygems.org/gems/ncurses

**Comment by otiai10** [comment]
TRY :  edit 'extconf.rb' following this http://totalrecall.wordpress.com/2010/08/22/ncurses-working-with-ruby-1-9-2-snow-leopard/

**Comment by otiai10** [comment]
```
% tree -f | rak extconf
13037||           |   |   |-- ./ruby/gems/1.8/gems/rb-appscript-0.6.1/extconf.rb
%
```
